# Generated by Django 5.0.1 on 2024-01-22 21:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Livro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('obra', models.CharField(max_length=100)),
                ('autor', models.CharField(max_length=100)),
                ('indice_catalogo', models.CharField(max_length=50)),
                ('editora', models.CharField(max_length=50)),
                ('edicao', models.CharField(max_length=12)),
                ('publicacao', models.IntegerField()),
                ('cidade', models.CharField(max_length=30)),
                ('pais_origem', models.CharField(max_length=20)),
                ('isbn', models.CharField(max_length=30)),
            ],
        ),
    ]
