# Generated by Django 5.0.1 on 2024-01-22 22:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('livro', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='livro',
            name='resenha',
            field=models.TextField(blank=True, null=True, verbose_name='Resenha'),
        ),
        migrations.AlterField(
            model_name='livro',
            name='autor',
            field=models.CharField(max_length=100, verbose_name='Autor'),
        ),
        migrations.AlterField(
            model_name='livro',
            name='cidade',
            field=models.CharField(max_length=30, verbose_name='Cidade'),
        ),
        migrations.AlterField(
            model_name='livro',
            name='edicao',
            field=models.CharField(max_length=12, verbose_name='Edição'),
        ),
        migrations.AlterField(
            model_name='livro',
            name='editora',
            field=models.CharField(max_length=50, verbose_name='Editora'),
        ),
        migrations.AlterField(
            model_name='livro',
            name='indice_catalogo',
            field=models.CharField(max_length=50, verbose_name='Indice Para Catalogo'),
        ),
        migrations.AlterField(
            model_name='livro',
            name='isbn',
            field=models.CharField(max_length=30, verbose_name='ISBN'),
        ),
        migrations.AlterField(
            model_name='livro',
            name='obra',
            field=models.CharField(max_length=100, verbose_name='Obra'),
        ),
        migrations.AlterField(
            model_name='livro',
            name='pais_origem',
            field=models.CharField(max_length=20, verbose_name='Pais de Origem'),
        ),
        migrations.AlterField(
            model_name='livro',
            name='publicacao',
            field=models.IntegerField(verbose_name='Publicação'),
        ),
    ]
