# Generated by Django 5.0.1 on 2024-05-03 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('livro', '0003_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='livro',
            name='cidade',
            field=models.CharField(max_length=50, verbose_name='Cidade'),
        ),
        migrations.AlterField(
            model_name='livro',
            name='editora',
            field=models.CharField(max_length=100, verbose_name='Editora'),
        ),
        migrations.AlterField(
            model_name='livro',
            name='indice_catalogo',
            field=models.CharField(max_length=100, verbose_name='Indice Para Catalogo'),
        ),
        migrations.AlterField(
            model_name='livro',
            name='isbn',
            field=models.CharField(max_length=40, verbose_name='ISBN'),
        ),
        migrations.AlterField(
            model_name='livro',
            name='pais_origem',
            field=models.CharField(max_length=50, verbose_name='Pais de Origem'),
        ),
    ]
